In [48]:
import pandas as pd
manifest = pd.read_csv(r'C:\Users\jaide\Downloads\intel_robotic_welding_dataset\manifest.csv')
manifest.head()

,CATEGORY,WELD_TYPE,THICKNESS_MM,STEEL_TYPE,SAMPLES,CURRENT_A,VOLTAGE_V,GAS_BAR,ROBOT_SPEED_CPM,DIRECTORY,SUBDIRS,SPLIT
0,Good,FILLET,7,FE410,19,165,21.0,4.5,25,2_good_weld_2_02-09-23_Fe410,2_good_weld_2_02-09-23_Fe410/04-01-23-0024-00,TRAIN
1,Good,NON_FILLET,7,FE410,20,160,22.0,4.0,30,good_weld_28_12-13-22_butt,good_weld_28_12-13-22_butt/12-13-22-0423-00,TRAIN
2,Good,NON_FILLET,7,FE410,20,150,19.0,4.0,30,good_weld_24_12-13-22_butt,good_weld_24_12-13-22_butt/12-13-22-0355-00,TRAIN
3,Good,NON_FILLET,7,FE410,20,170,22.0,4.0,30,good_weld_4_09-26-22_plane_plate,good_weld_4_09-26-22_plane_plate/09-26-22-0032-00,TRAIN
4,Good,NON_FILLET,7,FE410,20,165,21.0,4.0,30,good_weld_29_12-13-22_butt,good_weld_29_12-13-22_butt/12-13-22-0452-00,TRAIN

In [49]:
manifest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4040 entries, 0 to 4039
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CATEGORY         4040 non-null   object
 1   WELD_TYPE        4040 non-null   object
 2   THICKNESS_MM     4040 non-null   int64
 3   STEEL_TYPE       4040 non-null   object
 4   SAMPLES          4040 non-null   int64
 5   CURRENT_A        4040 non-null   int64
 6   VOLTAGE_V        4040 non-null   float64
 7   GAS_BAR          4040 non-null   float64
 8   ROBOT_SPEED_CPM  4040 non-null   int64
 9   DIRECTORY        4040 non-null   object
 10  SUBDIRS          4040 non-null   object
 11  SPLIT            4040 non-null   object
dtypes: float64(2), int64(4), object(6)
memory usage: 378.9+ KB

In [50]:
manifest['CATEGORY'].value_counts()

Good                                819
Excessive_Penetration               480
Porosity_w_Excessive_Penetration    480
Porosity                            340
Warping                             320
Burnthrough                         320
Lack_of_Fusion                      320
Spatter                             320
Crater_Cracks                       161
Excessive_Convexity                 160
Undercut                            160
Overlap                             160
Name: CATEGORY, dtype: int64

In [51]:
import os

BASE_PATH = r'C:\Users\jaide\Downloads\intel_robotic_welding_dataset'

Grouping Classes:

1. Good: Good

2. Porosity: Porosity_w_Excessive_Penetration,Porosity

3. Penetration: Excessive_Penetration, Excessive_Convexity

4. Surface Defects: Spatter, Overlap

5. Fusion Defects: Lack_of_Fusion, Burnthrough

6. Structural Defects: Warping, Crater_Cracks, Undercut

In [54]:
def group_classes(x):
    if x == 'Good':
        return 'Good'
    elif x in ['Porosity', 'Porosity_w_Excessive_Penetration']:
        return 'Porosity'
    
    elif x in ['Excessive_Penetration', 'Excessive_Convexity']:
        return 'Penetration'
    
    elif x in ['Spatter', 'Overlap']:
        return 'Surface'
    
    elif x in ['Lack_of_Fusion', 'Burnthrough']:
        return 'Fusion'
    
    elif x in ['Warping', 'Crater_Cracks', 'Undercut']:
        return 'Structural'
    
    else:
        return None

In [55]:
manifest['CATEGORY'] = manifest['CATEGORY'].apply(group_classes)

In [56]:
manifest['CATEGORY'].value_counts()

Porosity       820
Good           819
Structural     641
Fusion         640
Penetration    640
Surface        480
Name: CATEGORY, dtype: int64

In [58]:
manifest.drop(columns=['SPLIT','SAMPLES'], inplace = True)

In [60]:
manifest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4040 entries, 0 to 4039
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CATEGORY         4040 non-null   object
 1   WELD_TYPE        4040 non-null   object
 2   THICKNESS_MM     4040 non-null   int64
 3   STEEL_TYPE       4040 non-null   object
 4   CURRENT_A        4040 non-null   int64
 5   VOLTAGE_V        4040 non-null   float64
 6   GAS_BAR          4040 non-null   float64
 7   ROBOT_SPEED_CPM  4040 non-null   int64
 8   DIRECTORY        4040 non-null   object
 9   SUBDIRS          4040 non-null   object
dtypes: float64(2), int64(3), object(5)
memory usage: 315.8+ KB

In [62]:
manifest = pd.get_dummies(manifest, columns = ['STEEL_TYPE','WELD_TYPE'])

manifest.head()

,CATEGORY,THICKNESS_MM,CURRENT_A,VOLTAGE_V,GAS_BAR,ROBOT_SPEED_CPM,DIRECTORY,SUBDIRS,STEEL_TYPE_BSK46,STEEL_TYPE_FE410,WELD_TYPE_FILLET,WELD_TYPE_NON_FILLET
0,Good,7,165,21.0,4.5,25,2_good_weld_2_02-09-23_Fe410,2_good_weld_2_02-09-23_Fe410/04-01-23-0024-00,0,1,1,0
1,Good,7,160,22.0,4.0,30,good_weld_28_12-13-22_butt,good_weld_28_12-13-22_butt/12-13-22-0423-00,0,1,0,1
2,Good,7,150,19.0,4.0,30,good_weld_24_12-13-22_butt,good_weld_24_12-13-22_butt/12-13-22-0355-00,0,1,0,1
3,Good,7,170,22.0,4.0,30,good_weld_4_09-26-22_plane_plate,good_weld_4_09-26-22_plane_plate/09-26-22-0032-00,0,1,0,1
4,Good,7,165,21.0,4.0,30,good_weld_29_12-13-22_butt,good_weld_29_12-13-22_butt/12-13-22-0452-00,0,1,0,1

In [67]:
def get_csv_path(row):
    filename = row['SUBDIRS'].split('/')[-1] + ".csv"
    
    return os.path.join(BASE_PATH, row['SUBDIRS'],filename)

# base path + subdir + csv file

In [73]:
sample_file = get_csv_path(manifest.iloc[0])
pd.read_csv(sample_file)

,Date,Time,Part No,Pressure,CO2 Weld Flow,Feed,Primary Weld Current,Wire Consumed,Secondary Weld Voltage,Remarks
0,4/1/2023,05:22:48.385,04-01-23-0024-00,4.38,-0.01,0.02,0.0,0.98,0.0,NaN
1,4/1/2023,05:22:48.494,04-01-23-0024-00,4.38,0.01,0.02,0.0,1.15,0.0,NaN
2,4/1/2023,05:22:48.603,04-01-23-0024-00,4.38,0.00,0.02,0.0,1.15,0.0,NaN
3,4/1/2023,05:22:48.713,04-01-23-0024-00,4.38,0.01,0.02,0.0,1.15,0.0,NaN
4,4/1/2023,05:22:48.822,04-01-23-0024-00,4.38,-0.01,0.02,0.0,1.31,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...
330,4/1/2023,05:23:25.095,04-01-23-0024-00,2.15,2.97,0.16,0.0,5.90,0.0,NaN
331,4/1/2023,05:23:25.195,04-01-23-0024-00,2.15,2.70,0.16,0.0,5.90,0.0,NaN
332,4/1/2023,05:23:25.311,04-01-23-0024-00,2.15,0.02,0.16,0.0,5.90,0.0,NaN
333,4/1/2023,05:23:25.427,04-01-23-0024-00,2.78,0.00,0.16,0.0,5.90,0.0,NaN
334,4/1/2023,05:23:25.527,04-01-23-0024-00,2.78,0.02,0.16,0.0,5.90,0.0,NaN

In [74]:
import numpy as np

def extract_features(df):
    features = {}
    
    drop_cols = ['Date','Time','Part No', 'Remarks']
    df = df.drop(columns = [c for c in drop_cols if c in df.columns])
    df = df.loc[:, df.nunique() > 1]
    
    for col in df.columns:
        features[f'{col}_mean'] = df[col].mean()
        features[f'{col}_std'] = df[col].std()
        features[f'{col}_min'] = df[col].min()
        features[f'{col}_max'] = df[col].max()

    return features

In [75]:
final_data = []

for _, row in manifest.iterrows():
    path = get_csv_path(row)

    if os.path.exists(path):
        try:
            ts_df = pd.read_csv(path)
            ts_features = extract_features(ts_df)

            combined = row.to_dict()
            combined.update(ts_features)

            final_data.append(combined)

        except Exception as e:
            print(f"Error in {path}: {e}")

In [76]:
final_df = pd.DataFrame(final_data)
print(final_df.shape)

(4040, 36)

In [77]:
final_df.head()

,CATEGORY,THICKNESS_MM,CURRENT_A,VOLTAGE_V,GAS_BAR,ROBOT_SPEED_CPM,DIRECTORY,SUBDIRS,STEEL_TYPE_BSK46,STEEL_TYPE_FE410,...,Primary Weld Current_min,Primary Weld Current_max,Wire Consumed_mean,Wire Consumed_std,Wire Consumed_min,Wire Consumed_max,Secondary Weld Voltage_mean,Secondary Weld Voltage_std,Secondary Weld Voltage_min,Secondary Weld Voltage_max
0,Good,7,165,21.0,4.5,25,2_good_weld_2_02-09-23_Fe410,2_good_weld_2_02-09-23_Fe410/04-01-23-0024-00,0,1,...,0.0,193.30,3.677552,1.257343,0.98,5.90,12.830985,8.492224,0.0,40.23
1,Good,7,160,22.0,4.0,30,good_weld_28_12-13-22_butt,good_weld_28_12-13-22_butt/12-13-22-0423-00,0,1,...,0.0,197.05,722.036826,520.132619,12.79,1452.46,13.639162,10.272898,0.0,81.91
2,Good,7,150,19.0,4.0,30,good_weld_24_12-13-22_butt,good_weld_24_12-13-22_butt/12-13-22-0355-00,0,1,...,0.0,190.19,667.018795,486.358377,13.11,1355.08,14.256416,9.715918,0.0,81.90
3,Good,7,170,22.0,4.0,30,good_weld_4_09-26-22_plane_plate,good_weld_4_09-26-22_plane_plate/09-26-22-0032-00,0,1,...,0.0,196.48,903.518298,664.202286,9.34,1854.43,16.749818,10.683278,0.0,40.23
4,Good,7,165,21.0,4.0,30,good_weld_29_12-13-22_butt,good_weld_29_12-13-22_butt/12-13-22-0452-00,0,1,...,0.0,196.09,783.038114,577.300168,9.18,1598.69,15.231886,11.760270,0.0,81.92

In [78]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4040 entries, 0 to 4039
Data columns (total 36 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   CATEGORY                     4040 non-null   object
 1   THICKNESS_MM                 4040 non-null   int64
 2   CURRENT_A                    4040 non-null   int64
 3   VOLTAGE_V                    4040 non-null   float64
 4   GAS_BAR                      4040 non-null   float64
 5   ROBOT_SPEED_CPM              4040 non-null   int64
 6   DIRECTORY                    4040 non-null   object
 7   SUBDIRS                      4040 non-null   object
 8   STEEL_TYPE_BSK46             4040 non-null   int64
 9   STEEL_TYPE_FE410             4040 non-null   int64
 10  WELD_TYPE_FILLET             4040 non-null   int64
 11  WELD_TYPE_NON_FILLET         4040 non-null   int64
 12  Pressure_mean                4040 non-null   float64
 13  Pressure_std                 4040 non-null   float64
 14  Pressure_min                 4040 non-null   float64
 15  Pressure_max                 4040 non-null   float64
 16  CO2 Weld Flow_mean           4040 non-null   float64
 17  CO2 Weld Flow_std            4040 non-null   float64
 18  CO2 Weld Flow_min            4040 non-null   float64
 19  CO2 Weld Flow_max            4040 non-null   float64
 20  Feed_mean                    4040 non-null   float64
 21  Feed_std                     4040 non-null   float64
 22  Feed_min                     4040 non-null   float64
 23  Feed_max                     4040 non-null   float64
 24  Primary Weld Current_mean    4040 non-null   float64
 25  Primary Weld Current_std     4040 non-null   float64
 26  Primary Weld Current_min     4040 non-null   float64
 27  Primary Weld Current_max     4040 non-null   float64
 28  Wire Consumed_mean           4040 non-null   float64
 29  Wire Consumed_std            4040 non-null   float64
 30  Wire Consumed_min            4040 non-null   float64
 31  Wire Consumed_max            4040 non-null   float64
 32  Secondary Weld Voltage_mean  4040 non-null   float64
 33  Secondary Weld Voltage_std   4040 non-null   float64
 34  Secondary Weld Voltage_min   4040 non-null   float64
 35  Secondary Weld Voltage_max   4040 non-null   float64
dtypes: float64(26), int64(7), object(3)
memory usage: 1.1+ MB

In [79]:
final_df = final_df.drop(columns=['DIRECTORY', 'SUBDIRS'], errors='ignore')

In [80]:
X = final_df.drop(columns=['CATEGORY'])
y = final_df['CATEGORY']

In [81]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,shuffle=True)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=42)

In [82]:
model.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [83]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

     Fusion       0.99      1.00      1.00       127
       Good       1.00      0.99      1.00       183
Penetration       1.00      1.00      1.00       113
   Porosity       1.00      1.00      1.00       187
 Structural       1.00      1.00      1.00       110
    Surface       1.00      1.00      1.00        88

avg / total       1.00      1.00      1.00       808

In [84]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[127   0   0   0   0   0]
 [  1 182   0   0   0   0]
 [  0   0 113   0   0   0]
 [  0   0   0 187   0   0]
 [  0   0   0   0 110   0]
 [  0   0   0   0   0  88]]

In [89]:
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import accuracy_score

y_shuffled = np.random.permutation(y)

X_train, X_test, y_train, y_test = train_test_split(
    X, y_shuffled, test_size=0.2, random_state=42
)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Accuracy with shuffled labels:", accuracy_score(y_test, y_pred))

Accuracy with shuffled labels: 0.14975247524752475